name: test2

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: this will not fail.
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - id: cd
        run: cd test_dir && cat test.md
      - id: cat
        run: cat README.md
