name: test2

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: this will not fail.
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - id: cd
        run: cd test_dir && cat test.md
      - id: get_version
        run: echo "::set-output name=version::$(cat .version)"
      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.get_version.outputs.version }}
